project_id = "zrpknaltonashtvrfocb"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-powerbi-embed]
verify_jwt = false
